name: mimir

services:
  voi-node:
    platform: ${TARGETARCH:-linux/amd64}
    image: ghcr.io/voinetwork/voi-node:latest
    container_name: voi-follower-node
    environment:
      - VOINETWORK_NETWORK=mainnet
      - VOINETWORK_PROFILE=conduit
      - VOINETWORK_CATCHUP=0
    volumes:
      - type: bind
        source: ./algod-data
        target: /algod/data
    restart: always
    logging:
      driver: local
    networks:
      - voi-conduit-net

  conduit:
    platform: ${TARGETARCH:-linux/amd64}
    image: algorand/conduit:latest
    volumes:
      - ./conduit.yml:/etc/algorand/conduit.yml
    networks:
      - voi-conduit-net
      - supabase_default
    restart: always
    logging:
      driver: local
    depends_on:
      - voi-node

networks:
  voi-conduit-net:
    name: voi-conduit-net
    driver: bridge
  supabase_default:
    external: true
